<?php $__env->startSection('title',$title); ?>
<?php $__env->startSection('header'); ?>
<?php $__env->stopSection(); ?>
<section class="acerca-de">
    <?php $__env->startSection('pintor'); ?>
        <?php echo e($pintor); ?>

    <?php $__env->stopSection(); ?>
    <div class="info-container">
        <?php $__env->startSection('content'); ?>
            <div class="container-all">
                <img src="/img/leo.jpg" alt="">
                <h2>Biografía</h2>
                <p>
                    Considerado el paradigma del homo universalis, del sabio renacentista versado en todos los ámbitos del conocimiento humano, Leonardo da Vinci (1452-1519) incursionó en campos tan variados como la aerodinámica, la hidráulica, la anatomía, la botánica, la pintura, la escultura y la arquitectura, entre otros. Sus investigaciones científicas fueron, en gran medida, olvidadas y minusvaloradas por sus contemporáneos; su producción pictórica, en cambio, fue de inmediato reconocida como la de un maestro capaz de materializar el ideal de belleza en obras de turbadora sugestión y delicada poesía. <br>
                    <b>Recreación de un retrato de Leonardo </b> <br>
                    En el plano artístico, Leonardo conforma, junto con Miguel Ángel y Rafael, la tríada de los grandes maestros del Cinquecento, y, pese a la parquedad de su obra, la historia de la pintura lo cuenta entre sus mayores genios. Por los demás, es posible que de la poderosa fascinación que suscitan sus obras maestras (con La Gioconda a la cabeza) proceda aquella otra fascinación en torno a su figura que no ha cesado de crecer con los siglos, alimentada por los múltiples enigmas que envuelven su biografía, algunos de ellos triviales, como la escritura de derecha a izquierda, y otros ciertamente inquietantes, como aquellas visionarias invenciones cinco siglos adelantadas a su tiempo. <br>
                    <b>Juventud y descubrimientos técnicos </b> <br>
                    Leonardo nació en 1452 en la villa toscana de Vinci, hijo natural de una campesina, Caterina (que se casó poco después con un artesano de la región), y de Ser Piero, un rico notario florentino. Italia era entonces un mosaico de ciudades-estado como Florencia, pequeñas repúblicas como Venecia y feudos bajo el poder de los príncipes o el papa. El Imperio romano de Oriente cayó en 1453 ante los turcos y apenas sobrevivía aún, muy reducido, el Sacro Imperio Romano Germánico; era una época violenta en la que, sin embargo, el esplendor de las cortes no tenía límites. <br>
                    A pesar de que su padre se casaría cuatro veces, sólo tuvo hijos (once en total, con los que Leonardo entablaría pleitos por la herencia paterna) en sus dos últimos matrimonios, por lo que el pequeño Leonardo se crió como hijo único. Su enorme curiosidad se manifestó tempranamente: ya en la infancia dibujaba animales mitológicos de su propia invención, inspirados en una profunda observación del entorno natural en el que creció. Giorgio Vasari, su primer biógrafo, relata cómo el genio de Leonardo, siendo aún un niño, creó un escudo de Medusa con dragones que aterrorizó a su padre cuando se topó con él por sorpresa. <br>
                    Consciente del talento de su hijo, su padre le permitió ingresar como aprendiz en el taller de Andrea del Verrocchio. A lo largo de los seis años que el gremio de pintores prescribía como instrucción antes de ser reconocido como artista libre, Leonardo aprendió pintura, escultura y técnicas y mecánicas de la creación artística. El primer trabajo suyo del que se tiene certera noticia fue la construcción de la esfera de cobre proyectada por Brunelleschi para coronar la iglesia de Santa Maria dei Fiori. Junto al taller de Verrocchio, además, se encontraba el de Antonio Pollaiuolo, en donde Leonardo hizo sus primeros estudios de anatomía y, quizá, se inició también en el conocimiento del latín y el griego. <br>
                    Joven agraciado y vigoroso, Leonardo había heredado la fuerza física de la estirpe de su padre; es muy probable que fuera el modelo para la cabeza de San Miguel en el cuadro de Verrocchio Tobías y el ángel, de finos y bellos rasgos. Por lo demás, su gran imaginación creativa y la temprana pericia de su pincel no tardaron en superar a las de su maestro. En el Bautismo de Cristo, por ejemplo, los inspirados ángeles pintados por Leonardo contrastan con la brusquedad del Bautista hecho por Verrocchio. <br>
                    Ángeles atribuidos a Leonardo en el Bautismo de Cristo (c. 1475), de Andrea del Verrocchio <br>
                    El joven discípulo utilizaba allí por vez primera una novedosa técnica recién llegada de los Países Bajos: la pintura al óleo, que permitía una mayor blandura en el trazo y una más profunda penetración en la tela. Además de los extraordinarios dibujos y de la participación virtuosa en otros cuadros de su maestro, sus grandes obras de este período son un San Jerónimo y el gran panel La adoración de los Magos (ambos inconclusos), notables por el innovador dinamismo otorgado por la destreza en los contrastes de rasgos, en la composición geométrica de la escena y en el extraordinario manejo de la técnica del claroscuro. <br>
                    Florencia era entonces una de las ciudades más ricas de Europa; las numerosas tejedurías y los talleres de manufacturas de sedas y brocados de oriente y de lanas de occidente la convertían en el gran centro comercial de la península itálica; allí los Medici habían establecido una corte cuyo esplendor debía no poco a los artistas con que contaba. Pero cuando el joven Leonardo comprobó que no conseguía de Lorenzo el Magnífico más que alabanzas a sus virtudes de buen cortesano, a sus treinta años decidió buscar un horizonte más prospero. <br>
                    <b>Primer período milanés (1482-1499)</b> <br>
                    En 1482 se presentó ante el poderoso Ludovico Sforza, el hombre fuerte de Milán, en cuya corte se quedaría diecisiete años como «pictor et ingenierius ducalis». Aunque su ocupación principal era la de ingeniero militar, sus proyectos (casi todos irrealizados) abarcaron la hidráulica, la mecánica (con innovadores sistemas de palancas para multiplicar la fuerza humana) y la arquitectura, además de la pintura y la escultura. Fue su período de pleno desarrollo; siguiendo las bases matemáticas fijadas por Leon Battista Alberti y Piero della Francesca, Leonardo comenzó sus apuntes para la formulación de una ciencia de la pintura, al tiempo que se ejercitaba en la ejecución y fabricación de laúdes.Estimulado por la dramática peste que asoló Milán y cuya causa veía Leonardo en el hacinamiento y suciedad de la ciudad, proyectó espaciosas villas, hizo planos para canalizaciones de ríos e ingeniosos sistemas de defensa ante la artillería enemiga. Habiendo recibido de Ludovico el encargo de crear una monumental estatua ecuestre en honor de Francesco, el fundador de la dinastía Sforza, Leonardo trabajó durante dieciséis años en el proyecto del «gran caballo», que no se concretaría más que en un modelo en barro, destruido poco después durante una batalla. <br>
                    Resultó sobre todo fecunda su amistad con el matemático Luca Pacioli, fraile franciscano que hacia 1496 concluyó su tratado De la divina proporción, ilustrado por Leonardo. Ponderando la vista como el instrumento de conocimiento más certero con que cuenta el ser humano, Leonardo sostuvo que a través de una atenta observación debían reconocerse los objetos en su forma y estructura para describirlos en la pintura de la manera más exacta. De este modo el dibujo se convertía en el instrumento fundamental de su método didáctico, al punto que podía decirse que en sus apuntes el texto estaba para explicar el dibujo, y no al revés, razón por la que Leonardo da Vinci ha sido reconocido como el creador de la moderna ilustración científica. <br>
                    El ideal del saper vedere guió todos sus estudios, que en la década de 1490 comenzaron a perfilarse como una serie de tratados inconclusos que serían luego recopilados en el Codex Atlanticus, así llamado por su gran tamaño. Incluye trabajos sobre pintura, arquitectura, mecánica, anatomía, geografía, botánica, hidráulica y aerodinámica, fundiendo arte y ciencia en una cosmología individual que da, además, una vía de salida para un debate estético que se encontraba anclado en un más bien estéril neoplatonismo. <br>
                    Aunque no parece que Leonardo se preocupara demasiado por formar su propia escuela, en su taller milanés se creó poco a poco un grupo de fieles aprendices y alumnos: Giovanni Boltraffio, Ambrogio de Predis, Andrea Solari y su inseparable Salai, entre otros; los estudiosos no se han puesto de acuerdo aún acerca de la exacta atribución de algunas obras de este período, tales como la Madona Litta o el retrato de Lucrezia Crivelli. <br>
                    <b>Detalle de La Virgen de las Rocas (segunda versión, c. 1507)</b> <br>
                    Contratado en 1483 por la hermandad de la Inmaculada Concepción para realizar una pintura para la iglesia de San Francisco, Leonardo emprendió la realización de lo que sería la celebérrima Virgen de las Rocas, cuyo resultado final, en dos versiones, no estaría listo a los ocho meses que marcaba el contrato, sino veinte años más tarde. En ambas versiones la estructura triangular de la composición, la gracia de las figuras y el brillante uso del famoso sfumato para realzar el sentido visionario de la escena supusieron una revolución estética para sus contemporáneos. <br>
                    A este mismo período pertenecen el retrato de Ginevra de Benci (1475-1478), con su innovadora relación de proximidad y distancia, y la belleza expresiva de La belle Ferronnière. Pero hacia 1498 Leonardo finalizaba una pintura mural, en principio un encargo modesto para el refectorio del convento dominico de Santa Maria dalle Grazie, que se convertiría en su definitiva consagración pictórica: La Última Cena. Necesitamos hoy un esfuerzo para comprender su esplendor original, ya que se deterioró rápidamente y fue mal restaurada muchas veces. La genial captación plástica del dramático momento en que Jesucristo dice a los apóstoles «uno de vosotros me traicionará» otorga a la escena una unidad psicológica y una dinámica aprehensión del momento fugaz de sorpresa de los comensales (del que sólo Judas queda excluido). El mural se convirtió no sólo en un celebrado icono cristiano, sino también en un objeto de peregrinación para artistas de todo el continente. <br>
                    <b>El regreso a Florencia</b> <br>
                    A finales de 1499 los franceses entraron en Milán; Ludovico el Moro perdió el poder. Leonardo abandonó la ciudad acompañado de Pacioli y, tras una breve estancia en Mantua, en casa de su admiradora la marquesa Isabel de Este, llegó a Venecia. Acosada por los turcos, que ya dominaban la costa dálmata y amenazaban con tomar el Friuli, la Signoria de Venecia contrató a Leonardo como ingeniero militar. br
                    En pocas semanas proyectó una cantidad de artefactos cuya realización concreta no se haría sino, en muchos casos, hasta los siglos XIX o XX: desde una suerte de submarino individual, con un tubo de cuero para tomar aire destinado a unos soldados que, armados con taladro, atacarían a las embarcaciones por debajo, hasta grandes piezas de artillería con proyectiles de acción retardada y barcos con doble pared para resistir las embestidas. Los costes desorbitados, la falta de tiempo y, quizá, las pretensiones de Leonardo en el reparto del botín, excesivas para los venecianos, hicieron que las geniales ideas no pasaran de bocetos. En abril de 1500, tras casi veinte años de ausencia, Leonardo da Vinci regresó a Florencia. <br>
                    Dominaba entonces la ciudad César Borgia, hijo del papa Alejandro VI. Descrito por el propio Maquiavelo como «modelo insuperable» de intrigador político y déspota, este hombre ambicioso y temido se estaba preparando para lanzarse a la conquista de nuevos territorios. Leonardo, nuevamente como ingeniero militar, recorrió los territorios del norte, trazando mapas, calculando distancias precisas y proyectando puentes y nuevas armas de artillería. Pero poco después el condottiero cayó en desgracia: sus capitanes se sublevaron, su padre fue envenenado y él mismo cayó gravemente enfermo. En 1503 Leonardo volvió a Florencia, que por entonces se encontraba en guerra con Pisa, y concibió allí su genial proyecto de desviar el río Arno por detrás de la ciudad enemiga para cercarla, contemplando además la construcción de un canal como vía navegable que comunicase Florencia con el mar. El proyecto sólo se concretó en los extraordinarios mapas de su autor. <br>
                    <b>Santa Ana, la Virgen y el Niño (c. 1510)</b> <br>
                    Pero Leonardo ya era reconocido como uno de los mayores maestros de Italia. En 1501 había trazado un boceto de su Santa Ana, la Virgen y el Niño, que trasladaría al lienzo a finales de la década. En 1503 recibió el encargo de pintar un gran mural (el doble del tamaño de La Última Cena) en el palacio Viejo: la nobleza florentina quería inmortalizar algunas escenas históricas de su gloria. Leonardo trabajó tres años en La batalla de Anghiari, que quedaría inconclusa y sería luego desprendida por su deterioro. Pese a la pérdida, circularon bocetos y copias que admirarían a Rafael e inspirarían, un siglo más tarde, una célebre reproducción de Peter Paul Rubens. <br>
                    También sólo en copias sobrevivió otra gran obra de este periodo: Leda y el cisne. Sin embargo, la cumbre de esta etapa florentina (y una de las pocas obras acabadas por Leonardo) fue el retrato de Mona (abreviatura de Madonna) Lisa Gherardini, esposa de Francesco del Giocondo, razón por la que el cuadro es conocido como La Mona Lisa o La Gioconda. Obra famosa desde el momento de su creación, se convirtió en modelo de retrato y casi nadie escaparía a su influjo en el mundo de la pintura. Como cuadro y como personaje, la mítica Gioconda ha inspirado infinidad de libros y leyendas, y hasta una ópera; pero es poco lo que se conoce a ciencia cierta. Ni siquiera se sabe quién encargó el cuadro, que Leonardo llevaría consigo en su continua peregrinación vital hasta sus últimos años en Francia, donde lo vendió al rey Francisco I por cuatro mil piezas de oro. <br>
                    <b>Detalle de La Gioconda (c. 1503-1507)</b> <br>
                    Perfeccionando su propio hallazgo del sfumato, llevándolo a una concreción casi milagrosa, Leonardo logró plasmar un gesto entre lo fugaz y lo perenne: la «enigmática sonrisa» de la Gioconda es uno de los capítulos más admirados, comentados e imitados de la historia del arte, y su misterio sigue aún hoy fascinando. Existe la leyenda de que Leonardo promovía ese gesto en su modelo haciendo sonar laúdes mientras ella posaba; el cuadro, que ha atravesado no pocas vicisitudes, ha sido considerado como cumbre y resumen del talento y de la «ciencia pictórica» de su autor. <br>
                    <b>De nuevo en Milán (1506-1513)</b> <br>
                    El interés de Leonardo por los estudios científicos era cada vez más intenso. Asistía a disecciones de cadáveres, sobre los que confeccionaba dibujos para describir la estructura y funcionamiento del cuerpo humano; al mismo tiempo hacía sistemáticas observaciones del vuelo de los pájaros (sobre los que planeaba escribir un tratado), con la convicción de que también el hombre podría volar si llegaba a conocer las leyes de la resistencia del aire (algunos apuntes de este período se han visto como claros precursores del moderno helicóptero). <br>
                    Absorto por estas cavilaciones e inquietudes, Leonardo no dudó en abandonar Florencia cuando en 1506 Charles d'Amboise, gobernador francés de Milán, le ofreció el cargo de arquitecto y pintor de la corte; honrado y admirado por su nuevo patrón, Leonardo da Vinci proyectó para él un castillo y ejecutó bocetos para el oratorio de Santa Maria dalla Fontana, fundado por el mecenas. Su estadía milanesa sólo se interrumpió en el invierno de 1507, cuando colaboró en Florencia con el escultor Giovanni Francesco Rustici en la ejecución de los bronces del baptisterio de la ciudad. <br>
                    Quizás excesivamente avejentado para los cincuenta años que contaba entonces, su rostro fue tomado por Rafael como modelo del sublime Platón para su obra La escuela de Atenas. Leonardo, en cambio, pintaba poco, dedicándose a recopilar sus escritos y a profundizar en sus estudios: con la idea de tener finalizado para 1510 su tratado de anatomía, trabajaba junto a Marcantonio della Torre, el más célebre anatomista de su tiempo, en la descripción de órganos y el estudio de la fisiología humana. <br>
                    <b>Leonardo como Platón en La escuela de Atenas (1511), de Rafael</b> <br>
                    El ideal leonardesco de la «percepción cosmológica» se manifestaba en múltiples ramas: escribía sobre matemáticas, óptica, mecánica, geología, botánica; su búsqueda tendía hacia el encuentro de leyes, funciones y armonías compatibles para todas estas disciplinas, para la naturaleza como unidad. Paralelamente, a sus antiguos discípulos se sumaron algunos nuevos, entre ellos el joven noble Francesco Melzi, fiel amigo del maestro hasta su muerte. Junto a Ambrogio de Predis, Leonardo culminó hacia 1507 la segunda versión de La Virgen de las Rocas; poco antes, había dejado sin cumplir un encargo del rey de Francia para pintar dos madonnas. <br>
                    El nuevo hombre fuerte de Milán era entonces Gian Giacomo Trivulzio, quien pretendía retomar para sí el monumental proyecto del «gran caballo», convirtiéndolo en una estatua funeraria para su propia tumba en la capilla de San Nazaro Magiore; pero tampoco esta vez el monumento ecuestre pasó de los bocetos, lo que supuso para Leonardo su segunda frustración como escultor. En 1513 una nueva situación de inestabilidad política lo empujó a abandonar Milán; junto a Melzi y Salai marchó a Roma, donde se albergó en el belvedere de Giuliano de Médicis, hermano del nuevo papa León X. <br>
                    <b>Últimos años: Roma y Francia</b> <br>
                    En el Vaticano vivió una etapa de tranquilidad, con un sueldo digno y sin grandes obligaciones: dibujó mapas, estudió antiguos monumentos romanos, proyectó una gran residencia para los Médicis en Florencia y, además, reanudó su estrecha amistad con el gran arquitecto Donato Bramante, hasta el fallecimiento de éste en 1514. Pero en 1516, muerto su protector Giuliano de Médicis, Leonardo dejó Italia definitivamente para pasar los tres últimos años de su vida en el palacio de Cloux como «primer pintor, arquitecto y mecánico del rey». <br>
                    El gran respeto que le dispensó Francisco I de Francia hizo que Leonardo pasase esta última etapa de su vida más bien como un miembro de la nobleza que como un empleado de la casa real. Fatigado y concentrado en la redacción de sus últimas páginas para el nunca concluido Tratado de la pintura, cultivó más la teoría que la práctica, aunque todavía ejecutó extraordinarios dibujos sobre temas bíblicos y apocalípticos. Alcanzó a completar el ambiguo San Juan Bautista, un andrógino duende que desborda gracia, sensualidad y misterio; de hecho, sus discípulos lo imitarían poco después convirtiéndolo en un pagano Baco, que hoy puede verse en el Louvre de París. <br>
                    <b>Detalle de San Juan Bautista (c. 1516)</b> <br>
                    A partir de 1517 su salud, hasta entonces inquebrantable, comenzó a desmejorar. Su brazo derecho quedó paralizado; pero, con su incansable mano izquierda, Leonardo aún hizo bocetos de proyectos urbanísticos, de drenajes de ríos y hasta decorados para las fiestas palaciegas. Convertida en una especie de museo, su casa de Amboise estaba repleta de los papeles y apuntes que contenían las ideas de este hombre excepcional, muchas de las cuales deberían esperar siglos para demostrar su factibilidad y aun su necesidad; llegó incluso, en esta época, a concebir la idea de hacer casas prefabricadas. Sólo por las tres telas que eligió para que lo acompañasen en su última etapa (San Juan Bautista, La Gioconda y Santa Ana, la Virgen y el Niño) puede decirse que Leonardo poseía entonces uno de los grandes tesoros de su tiempo. <br>
                    El 2 de mayo de 1519 murió en Cloux; su testamento legaba a Melzi todos sus libros, manuscritos y dibujos, que el discípulo se encargó de retornar a Italia. Como suele suceder con los grandes genios, se han tejido en torno a su muerte algunas leyendas; una de ellas, inspirada por Vasari, pretende que Leonardo, arrepentido de no haber llevado una existencia regida por las leyes de la Iglesia, se confesó largamente y, con sus últimas fuerzas, se incorporó del lecho mortuorio para recibir, antes de expirar, los sacramentos.
                </p>
            </div>
            <h2 class="sub">Obras más importantes</h2>
        <?php $__env->stopSection(); ?>
        <div class="about-gallery">
            <?php $__env->startSection('obras'); ?>
                <img src="/img/l1.jpg" alt="">
                <img src="/img/l2.jpeg" alt="">
                <img src="/img/l3.jpg" alt="">
                <img src="/img/l4.jpg" alt="">
                <img src="/img/l5.jpg" alt="">
        </div>
        <br>
        <br>
        <br>
        <br>
        <?php $__env->stopSection(); ?>
    </div>
</section>
<?php $__env->startSection('footer'); ?>
    Copyright:<?php echo e(date('Y')); ?> - Liliana López
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.master', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\laragon\www\pintores\resources\views/l.blade.php ENDPATH**/ ?>